In [1]:
import numpy as np
import pandas as pd
import re

In [2]:
data=np.array([[1,2,3],
             [3,4,5],
             [6,7,8]])
data

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
data+5


array([[ 6,  7,  8],
       [ 8,  9, 10],
       [11, 12, 13]])

In [5]:
data-5


array([[-4, -3, -2],
       [-2, -1,  0],
       [ 1,  2,  3]])

In [6]:
data*5


array([[ 5, 10, 15],
       [15, 20, 25],
       [30, 35, 40]])

In [7]:
data/2


array([[0.5, 1. , 1.5],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [8]:
data%2

array([[1, 0, 1],
       [1, 0, 1],
       [0, 1, 0]], dtype=int32)

In [9]:
data=np.arange(0,11)
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
data=np.arange(2*3*10*10).reshape(2,3,10,10)
data

array([[[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
         [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
         [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
         [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
         [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
         [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
         [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
         [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
         [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
         [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]],

        [[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
         [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
         [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
         [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
         [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
         [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
         [160, 161, 16

In [13]:
data[0]

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]],

       [[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
        [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
        [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
        [160, 161, 162, 163, 164, 165,

In [15]:
a=np.arange(0,21,2)
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [18]:
print("shape", a.shape)

shape (11,)


In [24]:
a=np.array([[1,2,3,4],
           [5,6,7,8],
           [9,10,11,12]])
print("Shape",a.shape)# each dimension number axis
print("dimension",a.ndim)# total dimension axis
print("size",a.size)# total elemnts


Shape (3, 4)
dimension 2
size 12


# slicing

In [22]:
a[1][2]
#print("shape", a.shape)

7

In [23]:
a[1,2]

7

In [25]:
a[1]

array([5, 6, 7, 8])

In [26]:
a[2]

array([ 9, 10, 11, 12])

In [27]:
a[3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [28]:
a[0]# zero row all columns

array([1, 2, 3, 4])

In [29]:
a[:,0] #zero columns all rows

array([1, 5, 9])

In [30]:
a[:,-1]#last coumn all rows

array([ 4,  8, 12])

In [32]:
a[0,:]# zero rows all columns

array([1, 2, 3, 4])

In [33]:
a[1,:]# first row all columns

array([5, 6, 7, 8])

In [34]:
data=np.arange(10*10).reshape(10,10)
data

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [35]:
data[5:,5]

array([55, 65, 75, 85, 95])

In [36]:
data[5:,5]*5/2+3

array([140.5, 165.5, 190.5, 215.5, 240.5])

In [38]:
data[2:-2 ,2:-2]

array([[22, 23, 24, 25, 26, 27],
       [32, 33, 34, 35, 36, 37],
       [42, 43, 44, 45, 46, 47],
       [52, 53, 54, 55, 56, 57],
       [62, 63, 64, 65, 66, 67],
       [72, 73, 74, 75, 76, 77]])

In [39]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [49]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [40]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [51]:
np.ones(6, dtype=int)

array([1, 1, 1, 1, 1, 1])

In [41]:
data.shape

(10, 10)

In [42]:
np.ones_like(data)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [44]:
np.ones(data.shape)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [52]:
np.empty(10, dtype=int)

array([         0, 1080135680,          0, 1080340480,          0,
       1080545280,          0, 1080750080,          0, 1080954880])

In [47]:
np.empty_like(data)

array([[          0,           0,           0,           0,           0,
                  0, -1298876128,       32762,          46,           0],
       [-1006209040,         678, -1006208976,         678, -1006208848,
                678, -1006208784,         678, -1006208656,         678],
       [-1006208528,         678, -1006208400,         678, -1006208272,
                678, -1006208208,         678, -1006208336,         678],
       [-1006208144,         678, -1006208080,         678, -1006208016,
                678, -1006207952,         678, -1006207888,         678],
       [-1006207824,         678, -1006207760,         678, -1006207696,
                678, -1006207632,         678, -1006207568,         678],
       [-1006207504,         678, -1006207440,         678, -1006207376,
                678, -1006207312,         678, -1006207248,         678],
       [-1006207184,         678, -1006207120,         678, -1006207056,
                678, -1006206928,         678

# 1-2 ,generate between 1 and 2, total equal steps 5


In [54]:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [55]:
np.arange(1,2.25,0.25)


array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [56]:
np.linspace(1,2,4)


array([1.        , 1.33333333, 1.66666667, 2.        ])

# sorting


In [57]:
d = np.array([8,4,2,3,1,6,9,5,7,10])
d


array([ 8,  4,  2,  3,  1,  6,  9,  5,  7, 10])

In [58]:
np.sort(d)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
np.argsort(d)

array([4, 2, 3, 1, 7, 5, 8, 0, 6, 9], dtype=int64)

In [60]:
d.search.sorted(11)

AttributeError: 'numpy.ndarray' object has no attribute 'search'

In [61]:
list(enumerate([ 8 , 4,  2,  3,  1,  6,  9,  5,  7, 10]))


[(0, 8),
 (1, 4),
 (2, 2),
 (3, 3),
 (4, 1),
 (5, 6),
 (6, 9),
 (7, 5),
 (8, 7),
 (9, 10)]

In [62]:
print("raw d values",d)
np.argsort(d)


raw d values [ 8  4  2  3  1  6  9  5  7 10]


array([4, 2, 3, 1, 7, 5, 8, 0, 6, 9], dtype=int64)

In [63]:
d = np.array([8,4,2,3,1,6,9,5,7,10])
d.searchsorted(11)


10

In [64]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
print("a",a)
print("b",b)
np.concatenate((a,b))


a [1 2 3 4]
b [5 6 7 8]


array([1, 2, 3, 4, 5, 6, 7, 8])

In [65]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
print("a",a)
print("b",b)
np.vstack((a,b))


a [1 2 3 4]
b [5 6 7 8]


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [66]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
print("a",a)
print("b",b)
np.hstack((a,b))


a [1 2 3 4]
b [5 6 7 8]


array([1, 2, 3, 4, 5, 6, 7, 8])

In [67]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
print("a",a)
print("b",b)
np.stack((a,b),axis=0)


a [1 2 3 4]
b [5 6 7 8]


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [68]:
np.stack((a,b),axis=1)


array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [69]:
a = np.array([1, 2, 3, 4])
a[[True, False, False, True]]


array([1, 4])

# np.in1d


In [70]:
bank_cnic = np.arange(1,11)
bank_cnic

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [71]:
state_bank = np.array([100,75,7, 20, 125, 3])
state_bank


array([100,  75,   7,  20, 125,   3])

In [72]:
np.in1d(state_bank, bank_cnic)

array([False, False,  True, False, False,  True])

In [73]:
state_bank[np.in1d(state_bank, bank_cnic)]


array([7, 3])

In [74]:
np.intersect1d(state_bank,bank_cnic)


array([3, 7])

# task


In [75]:
a = np.arange(20*5).reshape((20,5))
a


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [76]:
a % 3 == 0


array([[ True, False, False,  True, False],
       [False,  True, False, False,  True],
       [False, False,  True, False, False],
       [ True, False, False,  True, False],
       [False,  True, False, False,  True],
       [False, False,  True, False, False],
       [ True, False, False,  True, False],
       [False,  True, False, False,  True],
       [False, False,  True, False, False],
       [ True, False, False,  True, False],
       [False,  True, False, False,  True],
       [False, False,  True, False, False],
       [ True, False, False,  True, False],
       [False,  True, False, False,  True],
       [False, False,  True, False, False],
       [ True, False, False,  True, False],
       [False,  True, False, False,  True],
       [False, False,  True, False, False],
       [ True, False, False,  True, False],
       [False,  True, False, False,  True]])

In [77]:
a[a % 3 == 0]


array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [78]:
(a % 3 == 0 ) & (a % 5 == 0)


array([[ True, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [ True, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [ True, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [ True, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [ True, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [ True, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [ True, False, False, False, False],
       [False, False, False, False, False]])

In [79]:
a[(a % 3 == 0 ) & (a % 5 == 0)]


array([ 0, 15, 30, 45, 60, 75, 90])

In [80]:
a[(a % 3 == 0 ) & (a % 5 == 0) & (a % 6 == 0)]


array([ 0, 30, 60, 90])

In [81]:
b = np.arange(11)
print(b)
b < 5


[ 0  1  2  3  4  5  6  7  8  9 10]


array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False])

In [82]:
b = np.arange(11)
print(b)
b % 2


[ 0  1  2  3  4  5  6  7  8  9 10]


array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0], dtype=int32)

In [83]:
b = np.arange(11)
print(b)
b % 2 == 0


[ 0  1  2  3  4  5  6  7  8  9 10]


array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True])

In [84]:
b[~(b % 2 == 0)]


array([1, 3, 5, 7, 9])

In [85]:
b[b % 2 == 0]


array([ 0,  2,  4,  6,  8, 10])

# attendance


In [86]:
x = """
Muhammad Atique Qayyum2:01 PM
yes can hear you clearly
Syed Ammad Waheed2:07 PM
syed ammad waheed hassani 4210113863591
Mohsin Kanani2:08 PM
4230108335683
Muhammad faizan Farooque2:08 PM
4230139662957
Zeeshan Javed2:08 PM
4230189725317
Afnan Ali2:08 PM
Muhammad Afnan Ali Khan 4210146436547
Wasiq Gt2:08 PM
4250104502069
Syed Rafiq ul Hoda2:09 PM
4210107768583
Abdul Samad Siddiqui2:09 PM
4250164941763
Saba Naz2:09 PM
42501-2598780-8
Muhammad Ali Syed Sadiqullah2:09 PM
42501-0528690-7
Hassan Ahmed2:09 PM
4220156089133
Qazi Moawiz2:09 PM
3130399221225
Khawar Masood2:09 PM
42101-4113797-7
syed daniyal Ejaz2:09 PM
please speak loud sir
Mushyada Ali2:09 PM
4210103553847
Dewan S Khan2:09 PM
4220105630741
Muhammad Ayaz2:09 PM
4410242997959
Rahat Qayoum EB20_110 (20102110)2:10 PM
4240128161338
Tatheer Fatima2:10 PM
4210124609792
Nofil Ahmed2:10 PM
4210175076663
Hassan Khan2:10 PM
4240160019477
Sumayya Kamran EB20_125 (EB20102125)2:10 PM
42501-0654455-2
syed daniyal Ejaz2:10 PM
4250189782769
manal khan2:10 PM
4210170238438
Sania Tehseen2:11 PM
4210115022744
Muhammad Sameer2:13 PM
4250110257001
zain abidi2:15 PM
4250119167549
syed daniyal Ejaz2:22 PM
voice issue sir please speak load sir thanks
Loud*
Muneeb Ahmed2:22 PM
42101-8342718-3
Afnan Ali2:22 PM
sahi arhi ha awaz
Muhammad Atique Qayyum2:22 PM
your voice is clear to me
Khawar Masood2:23 PM
voice is so clear sir
Dewan S Khan2:23 PM
sir plz again
Muhammad Atique Qayyum2:33 PM
sir to much distortion
Munir Ali2:33 PM
distortion in voice sir
Mushyada Ali2:33 PM
your voice is breaking
Muneeb Ahmed2:34 PM
voice distortion
Muhammad Atique Qayyum2:34 PM
yes still breaking
no
Wasiq Gt2:35 PM
yes
Muhammad Ayaz2:35 PM
yes sir
Hassan Khan2:35 PM
Yes sir
Ad Khan2:38 PM
Muhammad Adnan Khan 4220113823383
Syed Usama Shahzad2:38 PM
4210134163079
Khawar Masood2:40 PM
no voice from your side sir
Muhammad faizan Farooque2:40 PM
no voice
Muhammad Atique Qayyum2:40 PM
can't hear you sir
Shakir Hussain2:42 PM
Sir your screen is not shared
Rozina Mazhar Ali2:42 PM
it is shared
Muhammad faizan Farooque2:42 PM
it is shared and visible
Shakir Hussain2:43 PM
It's shared now
Syed Kashif2:50 PM
42501-4448854-5
Rozina Mazhar Ali2:51 PM
4220159083880
Faiza Asad2:51 PM
4200052746960
Muneeb Ahmed2:57 PM
42101-8342718-3\
Tabish sheikh3:22 PM
4210129511133
usman ahmad3:22 PM
4220113316709
Arsalan Ahmed3:22 PM
4220165351957
Syed Tanveer3:22 PM
4220169252467
Muhammad faizan Farooque3:22 PM
4230139662957
Shakir Hussain3:22 PM
4210182767349
Zeeshan Naqvi3:23 PM
4210151751811
Rao Taha3:23 PM
4220172475489
Khizra Rizvi3:24 PM
5440047459326
Zahid Bashir3:24 PM
4250191411023
HAREEM RIZVI3:26 PM
42101-3311570-4
Syed Ali3:26 PM
Syed Masroor Ali 42401-1880106-5
Syed Usama Shahzad3:35 PM
4210134163079
Syed Kashif3:37 PM
42501-4448854-5
Tariq Mehmood3:38 PM
4220104505899
Hassan Khan3:38 PM
4240160019477
Mohsin Kanani3:38 PM
4230108335683
Dewan S Khan3:45 PM
4220105630741
Shoaib Abdul Razzaque3:46 PM
5140176791651
Syed Usama Shahzad3:49 PM
4210134163079
Bilal Ahmed3:50 PM
4210120075463
Muhammad Sameer3:53 PM
No sir
Syed Usama Shahzad3:57 PM
4210134163079
Nazneen Akram3:57 PM
4210145447712
Bilal Ahmed3:57 PM
4210120075463
Munir Ali3:57 PM
4220101410369
Zareen Fatima3:57 PM
3520269403788
Muhammad Atique Qayyum3:57 PM
4220140225263
Wasiq Gt3:57 PM
4250104502069
Haris Chhipa3:57 PM
4210156195059
Qazi Moawiz3:57 PM
3130399221225
Shakir Hussain3:57 PM
4210182767349
Dewan S Khan3:57 PM
4220105630741
Yusra Adnan3:57 PM
4210164790696
Syed Ali3:57 PM
Syed Masroor Ali, 42401-1880106-5
Zeeshan Naqvi3:58 PM
4210151751811
Nazneen Akram3:58 PM
4210145447712
Syed Rafiq ul Hoda3:58 PM
4210107768583
Syed Muhammad Abdullah3:58 PM
4220122868467 Syed Muhammad Abdullah
Hassan Khan3:58 PM
4240160019477
Muhammad Ayaz3:58 PM
4410242997959
Zeeshan Javed3:58 PM
4230189725317
Asima Ali3:58 PM
4420626938874
Faiza Asad3:58 PM
4200052746960
Syed Tanveer3:58 PM
4220169252467
Tabassum Ali3:58 PM
4230123126547
Shoaib Abdul Razzaque3:58 PM
5140176791651
Fazal Diyan3:58 PM
42301-9945992-1
Sania Tehseen3:58 PM
4210115022744
Sumayya Kamran EB20_125 (EB20102125)3:58 PM
4250106544552
Muhammad Sameer3:58 PM
4250110257001
Muhammad Ali Syed Sadiqullah3:58 PM
4250105286907
Shakir Hussain3:58 PM
4210182767349
Mushyada Ali3:59 PM
4210103553847
manal khan3:59 PM
4210170238438
Afnan Ali3:59 PM
Muhammad Afnan Ali Khan 4210146436547
Nofil Ahmed3:59 PM
4210175076663
"""

x = x.replace("-","")
import re
cnic = re.findall(r"\b\d{13}\b",x)
print(len(cnic))
cnic = list(set(cnic))
print(len(cnic))


import pandas as pd
df = pd.DataFrame(cnic, columns=["CNIC"])
df


88
56


CNIC
0   4210164790696
1   4210120075463
2   4220113316709
3   4210175076663
4   4240118801065
5   4410242997959
6   4230189725317
7   4210103553847
8   4210115022744
9   4210156195059
10  4210170238438
11  3130399221225
12  4220122868467
13  4210145447712
14  4220165351957
15  4220169252467
16  4210183427183
17  4210134163079
18  4250144488545
19  4220156089133
20  4210182767349
21  4250119167549
22  4250105286907
23  4230123126547
24  4250106544552
25  5440047459326
26  4250110257001
27  4220104505899
28  4210124609792
29  4250125987808
30  4220140225263
31  4210146436547
32  4250164941763
33  4230199459921
34  4230139662957
35  4220101410369
36  4210133115704
37  4250189782769
38  4420626938874
39  4210129511133
40  4220159083880
41  4210113863591
42  4220113823383
43  4250191411023
44  4230108335683
45  3520269403788
46  4210141137977
47  4220172475489
48  4240128161338
49  4220105630741
50  4210151751811
51  4210107768583
52  4200052746960
53  4250104502069
54  5140176791651
55  4240160019477